title: plumgaming
description: plumgaming-jp.com Repository
theme: just-the-docs

url: https://plumgaming-jp.com

encoding: UTF-8

include:
  - _headers

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

plugins:
  # - jekyll-sitemap
