title: plumgaming
description: plumgaming-jp.com Repository
theme: just-the-docs

url: https://plumgaming-jp.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

encoding: UTF-8

include:
  - _headers

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
